# .github/workflows/pages.yml
name: Deploy KB CSS

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: write
  pages:    write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # DEV ➜ /dev  (preview)                                          #
      - name: Deploy dev branch → /dev
        if: github.ref == 'refs/heads/dev'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          target-folder: dev
          clean: false

      # MAIN ➜ root  (production)                                      #
      - name: Deploy main branch → site root
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true
          clean-exclude: |
            dev/**
